export default {
  Song: [
    {
      id: "1",
      title: "Song One",
      artist_id: "1",
      album_id: "1",
      genres: ["Pop", "Rock"],
    },
    {
      id: "2",
      title: "Song Two",
      artist_id: "2",
      album_id: "2",
      genres: ["Jazz"],
    },
    {
      id: "3",
      title: "Song Three",
      artist_id: "3",
      album_id: "3",
      genres: ["Classical"],
    },
    {
      id: "4",
      title: "Song Four",
      artist_id: "1",
      album_id: "1",
      genres: ["Pop"],
    },
    {
      id: "5",
      title: "Song Five",
      artist_id: "2",
      album_id: "2",
      genres: ["Rock"],
    },
    {
      id: "6",
      title: "Song Six",
      artist_id: "3",
      album_id: "3",
      genres: ["Hip-Hop"],
    },
    {
      id: "7",
      title: "Song Seven",
      artist_id: "1",
      album_id: "1",
      genres: ["Electronic"],
    },
  ],
  Artist: [
    {
      id: "1",
      name: "Artist One",
      country: "USA",
      song_ids: ["1", "4", "7"],
    },
    {
      id: "2",
      name: "Artist Two",
      country: "UK",
      song_ids: ["2", "5"],
    },
    {
      id: "3",
      name: "Artist Three",
      country: "Canada",
      song_ids: ["3", "6"],
    },
    {
      id: "4",
      name: "Artist Four",
      country: "Australia",
      song_ids: [],
    },
    {
      id: "5",
      name: "Artist Five",
      country: "India",
      song_ids: [],
    },
    {
      id: "6",
      name: "Artist Six",
      country: "Germany",
      song_ids: [],
    },
    {
      id: "7",
      name: "Artist Seven",
      country: "France",
      song_ids: [],
    },
  ],
  Album: [
    {
      id: "1",
      title: "Album One",
      release_year: 2020,
      artist_id: "1",
      song_ids: ["1", "4", "7"],
    },
    {
      id: "2",
      title: "Album Two",
      release_year: 2019,
      artist_id: "2",
      song_ids: ["2", "5"],
    },
    {
      id: "3",
      title: "Album Three",
      release_year: 2021,
      artist_id: "3",
      song_ids: ["3", "6"],
    },
    {
      id: "4",
      title: "Album Four",
      release_year: 2018,
      artist_id: "1",
      song_ids: [],
    },
    {
      id: "5",
      title: "Album Five",
      release_year: 2017,
      artist_id: "2",
      song_ids: [],
    },
    {
      id: "6",
      title: "Album Six",
      release_year: 2022,
      artist_id: "3",
      song_ids: [],
    },
    {
      id: "7",
      title: "Album Seven",
      release_year: 2023,
      artist_id: "1",
      song_ids: [],
    },
  ],
};
